### ISSUE TITLE
Create some way to annotate `next()` function

### ISSUE THREAD

**Issue by neurosnap** [jimbol/expect-gen#1]
On one hand it is nice we don't have to do `next('someEffect')` but when there are multiple `next()` in a row, it's hard to understand what next corresponds to what effect.

It would be nice if we could have an optional way to annotate the next.

**Comment by jimbol** [comment]
Could be helpful, an alternative `next` method could do the trick, perhaps `namedNext(name, ...args)` or something along those lines?

**Comment by neurosnap** [comment]
Yeah or maybe just adding a comment would be good enough.

```js
expectGen()
  .next() // select(getUsers)
  .next() // put(something)
```

**Comment by jimbol** [comment]
Could use a second argument

```es6
.next(users, 'select(getUsers)')
.next(null, 'put(something)')
```
