### ISSUE TITLE
Adding matcher for array yields

### ISSUE THREAD

**Issue by flushentitypacket** [jimbol/expect-gen#11]
Since redux-saga allows you to `yield [effect1, effect2]` to run in parallel, it might be convenient to be able to have `yields(effect1)` match.

**Comment by jimbol** [comment]
Thanks for the comment!
The current approach to test this would be:
```.yields([effect1, effect2])```
Is this what you're getting at?

**Comment by flushentitypacket** [comment]
Yes, exactly!

**Comment by jimbol** [comment]
Ok, so you'd rather do `.yields(effect1)` instead of `.yields([effect1, effect2])`?

**Comment by flushentitypacket** [comment]
Yeah, I think that makes testing a bit easier (we don't typically care about concurrency optimizations on the expectation/testing side of things). On the flipside, it could be a gotcha in some circumstances.

**Comment by jimbol** [comment]
I think a separate method would be better.  Something like 
```es6
.assert((yieldedVal) => yieldedVal[0] === effect1)
```

consider non-redux use cases
```es6
.yields(1)
```
should not succeed for `yield [1, 2, 3]`

**Comment by flushentitypacket** [comment]
Yeah, that's true. I just think it'd be nice to be able to do something like: write tests that pass, then go back and add some concurrency optimizations.

Since this lib is trying to preserve the ability to test non-redux-saga gen fns, this feature probably doesn't make sense.

**Comment by jimbol** [comment]
Closing this issue
