### ISSUE TITLE
API to handle generator errors

### ISSUE THREAD

**Issue by jupl** [jimbol/expect-gen#15]
See example for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/throw

**Comment by jimbol** [comment]
I'm thinking

### throws
```es6
expectGen(generator, [...args])
  .throws(error)
```
- Throws `error` into generator
- Checks that iterator throws an uncaught exception
- Returns same instance `StepManager`

### catches
```es6
expectGen(generator, [...args])
  .catches(error, [expectedValue])
```
- Throws `error` into generator
- Runs an assertion that thrown iterator will yield the `expectedValue`
- Returns same instance `StepManager`

### catchesAndFinishes
```es6
expectGen(generator, [...args])
  .catchesAndFinishes(error, [result])
```
- Asserts that generator finishes with `result`
- Returns same instance `StepManager`

**Comment by jimbol** [comment]
This has been released. 

Further improvements will be made via https://github.com/jimbol/expect-gen/issues/17
