### ISSUE TITLE
If Run time error occurs, log error

### ISSUE THREAD

**Issue by baldwmic** [jimbol/expect-gen#22]
it would be nice to log runtime errors instead of swallowing them so the end-user can see what went wrong.

I had a generator function and I passed the wrong properties in causing a runtime error in my code, but expectGen swallowed the error.

**Comment by jimbol** [comment]
This _might_ be related to the `describe` block code. I'll investigate more.

**Comment by jimbol** [comment]
After some testing, that was NOT the problem. I was just formatting the call stack without the message.

Should be fixed with this PR.
