### ISSUE TITLE
Serializing redux-saga `select`

### ISSUE THREAD

**Issue by neurosnap** [jimbol/expect-gen#9]
When we serialize selectors into JSON we get the following output:

```js
Object {
    "done": false,
    "value": Object {
      "@@redux-saga/IO": true,
      "SELECT": Object {
        "args": Array [],
      },
    },
  },
```

This doesn't really tell us much.  Do we care what selector we are trying to use in the snapshot?

We could create a custom serializer to help spell out what exact it is we are selecting.  http://facebook.github.io/jest/docs/en/expect.html#expectaddsnapshotserializerserializer

**Comment by jimbol** [comment]
This should be a separate library. A serializer like this won't be useful for those testing raw generators.
